### ISSUE TITLE
Concatenate string with tags introduces funny spaces in html

### ISSUE THREAD

**Issue by spapas** [ruricolist/spinneret#101]
I wanna create something simple like this:

```lisp
(:span "You are logged in as " (:b (ht:session-value :username)) ".")
```

Unfortunately, the above will output a funny space before the dot in the html:

```html
<span>You are logged in as <b>root1</b> .</span>
```

Now, if I try something like this instead:

```lisp
(:span (:span "You are logged in as ") (:b (ht:session-value :username)) (:span "."))
```

It will output the dot where it needs to be, however it will add unnecessary spans. Also I could use `raw`:

```lisp
(:raw (format nil "You are logged in as <b>~A</b>." (ht:session-value :username)))
```

However I'd prefer to format this properly with spinneret. Is it possible somehow ?

**Comment by ruricolist** [comment]
This specific problem should be fixed now.

**Comment by spapas** [comment]
Works great now thank you!
