### ISSUE TITLE
Feature request: runtime generation of tags

### ISSUE THREAD

**Issue by fiddlerwoaroof** [ruricolist/spinneret#16]
I'd like to be able to leave a tag unfilled at compile time and then generate it at run time. For example, I'd like to be able to automatically create the appropriate h1-h6 tag based on the value of a dynamic variable, something like:

```common-lisp
(defvar *nesting-level* 1)
(spinneret:deftag section (...)
  `(:section (spinneret:dynamic-tag ((format nil "H~d" *nesting-level*))
                    "The heading")
     (let ((*nesting-level* (1+ *nesting-level*))
       ,@body))
(spinneret:with-html
  (section (section "test")))
```

should generate something like

```html
<section>
  <h1>The heading</h1>
  <section>
    <h1>The heading</h1>
    test
  </section>
</section>
```

I can do this right now by doing something like
```common-lisp
(format spinneret:*html* "<H~d>~a</H~@*~d>" *nesting-level* "The heading")
```
But that seems a bit inelegant: (a) it seems to be doing stuff at a lower-level than the rest of the surrounding code and (b) it doesn't interact well with the pretty printer.

**Comment by ruricolist** [comment]
To be clear, do you actually need full support for dynamic tags, or would a specific solution to the problem of nesting headings be acceptable?

**Comment by fiddlerwoaroof** [comment]
That would work too for my current purposes.

**Comment by ruricolist** [comment]
This is in Spinneret now. There is support for dynamic tags (using the `:tag` pseudo-tag) and a specific pseudo-tag for this particular use case (`:h*`). The README has the details.

**Comment by fiddlerwoaroof** [comment]
Great, thanks!
