### ISSUE TITLE
Lispwork no-break space

### ISSUE THREAD

**Issue by fiddlerwoaroof** [ruricolist/spinneret#18]
On Lispworks, the character name of the non-breaking space is `no-break-space`, on sbcl it's `no-break_space`.  However, all the implementations I've tried recognize #\u+00a0 as the same character.

**Comment by PuercoPop** [comment]
@fiddlerwoaroof `#\u...` relies on the implementation supporting unicode.  The standard [only guarantee few names of characters](http://www.lispworks.com/documentation/HyperSpec/Body/13_ag.htm). So Neither `#\no-break-space` or `#\non-breaking-space` are codes are [portable common lisp](http://www.lispworks.com/documentation/HyperSpec/Body/26_glo_p.htm#portable). However most implementations have adopted the unicode names for characters, which in this case is [no-break-space](http://www.fileformat.info/info/unicode/char/00a0/index.htm). I wonder why Lispworks isn't doing the same?

**Comment by fiddlerwoaroof** [comment]
lispworks almost has the same name as sbcl and ccl, on lispworks it's `#\no-break-space` on sbcl and ccl it's `#\no-break_space`. So, for portability, the options would either be to use reader conditionals.

As far as unicode support goes, isn't that a reasonable assumption for web-oriented software, especially for a library that has "being modern" as one of its goals?

**Comment by fiddlerwoaroof** [comment]
I suppose the alternative is just using `#.(code-char 160)`

**Comment by PuercoPop** [comment]
@fiddlerwoaroof If it is reasonable to asume unicode, wouldn't that include using the unicode character names, which lispworks doesn't? imho this is an issue with Lispworks. Btw, I was just chiming in my 2c. I'd assume @ruricolist will add a reader conditional.

**Comment by fiddlerwoaroof** [comment]
The only difference between lispworks's character names and sbcl's is that lispworks has a `-` where sbcl (and all the other open source implementations I've tested) has a `_`.

**Comment by PuercoPop** [comment]
Ah, sorry, I had misread the lispworks name to non-breaking space

**Comment by ruricolist** [comment]
I've pushed a reader conditional solution as a `lispworks` branch. I couldn't get far enough with the Personal Edition to test it myself, so I will have to rely on you to tell me if it loads properly under LispWorks.

**Comment by fiddlerwoaroof** [comment]
@ruricolist that fixes it.  The personal edition is a bit of a pain because it uses ASDF < 3, so you have to upgrade ASDF before installing quicklisp and, even then, it doesn't always work reliably.

**Comment by ruricolist** [comment]
The branch with the fix is merged.
