### ISSUE TITLE
Does not build in latest SBCL - symbol issue

### ISSUE THREAD

**Issue by quicklisp** [ruricolist/spinneret#19]
I get a lot of these:

    ; caught ERROR:
    ;   during macroexpansion of (DEFINE-TAG :A). Use *BREAK-ON-SIGNALS* to intercept.
    ;    The value "<a" is not of type (SIMPLE-ARRAY CHARACTER (*)) from the function type declaration.

It's due to how sbcl 1.3.19 treats symbol-name strings.

**Comment by ruricolist** [comment]
This should be fixed now.
