### ISSUE TITLE
Interesting Coincidence

### ISSUE THREAD

**Issue by SlightlyCyborg** [ruricolist/spinneret#22]
The company I work for builds machines to inspect spinnerets for producing man made fibers. I took up the task of cataloging the spinnerets. I went searching for a common lisp HTML 5 generator for the project and ironically, this library came up! 

PS: This bumps up the Baysian probability in the belief that '(I am a time traveling alien that likes to mess with my past self using Github) from 0.5% likelihood to 1% likelihood .

**Comment by ruricolist** [comment]
This is the part where I tell you about the mysterious stranger who gave me the idea in the first place, right?

**Comment by SlightlyCyborg** [comment]
Haha! Sure.

`(incf (slot-value *current-hypothesis* 'baysian-probability) .2)`
