### ISSUE TITLE
HTML literals?

### ISSUE THREAD

**Issue by SlightlyCyborg** [ruricolist/spinneret#23]
Hi. Is there a way to include arbitrary HTML into `(with-html-string)`. It is escaping the < and >. It is nice to paste html from the web into my site.

**Comment by ruricolist** [comment]
You can use the `:raw` pseudotag for that.

**Comment by SlightlyCyborg** [comment]
Thanks!

**Comment by SlightlyCyborg** [comment]
Thanks!
