### ISSUE TITLE
Compile-File-Error in sbcl version 1.4.8

### ISSUE THREAD

**Issue by sabracrolleton** [ruricolist/spinneret#24]
sbcl version 1.4.8

    (ql:quickload :spinneret)

To load "spinneret":
  Load 1 ASDF system:
    spinneret
; Loading "spinneret"
..................................................
[package string-case].
; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Lock on package SB-VM violated when interning XOR while in package
;     STRING-CASE.
;   See also:
;     The SBCL Manual, Node "Package Locks"
;   
;     (in form starting at line: 246, column: 0, position: 10257)

Have not tried other versions of sbcl

**Comment by sabracrolleton** [comment]
Problem is in string-case (which is pulled in by depending on serapeum) and latest version of sbcl. It has been flagged as an issue in that package. Not sure what users can do about it until string-case is fixed.

**Comment by ruricolist** [comment]
I'm pretty sure string-case is BSD, so if it doesn't get fixed in the
nearish future I'll incorporate a fixed version into Serapeum.

**Comment by ruricolist** [comment]
This has been fixed upstream, so I'm closing this issue.
