### ISSUE TITLE
There are some unused imports from serapeum

### ISSUE THREAD

**Issue by PuercoPop** [ruricolist/spinneret#26]
- SERAPEUM:STRING+ unused as of fe6192aca3134566a18018343f8d26981494b404
- SERAPEUM:UNSPLICE unused as of 7bae1722fe9bc18e66937aea66104930e71172b5
- SERAPEUM:RECEIVE unused as of f397575
- SERAPEUM:DEFSUBST which appears to never have been used

**Comment by ruricolist** [comment]
I've removed these, but if you don't mind me asking, how did you come to discover them?

**Comment by PuercoPop** [comment]
I was looking for examples of how functions of Serapeum were used and the coincidentally first one I searched for, `unsplice`, was unused so I checked for others.

Incidentally I wanted to ask to you about `unsplice`, Although the extra wrapping parens about the code are not exactly tasteful is the extra nesting to do away with extra parens more tasteful? Even though I dislike boilerplate in Lisp, at least the pattern `,@(when …)` is easy to recognize. I know that the word 'tasteful' is subjective but still I'm curious to know why/if you prefer `unsplice`.

**Comment by ruricolist** [comment]
I think unsplice is a clear improvement when you’re splicing in a variable:

``` lisp
,@(and docstring `(,docstring))
,@(unsplice docstring)
```

It’s not as compelling where there’s an explicit condition, but I still prefer it. I think of it as future-proofing: there’s less danger of introducing a bug if I come back later and edit the code. Especially if there’s more than one branch.
