### ISSUE TITLE
parenscript funtionality separated

### ISSUE THREAD

**Issue by mfiano** [ruricolist/spinneret#32]
Would it at all be possible to separate the parenscript functionality into a secondary asdf system? I do not use parenscript, infact I found a bug in parenscripts code that causes Sly (a SLIME fork) to hang and eventually error when completing symbols, because parenscript is wrongly importing a symbol with no home package.

**Comment by ruricolist** [comment]
That's doable.

I'm a Sly user myself, so thanks for reporting the problem there as well.
