### ISSUE TITLE
Infinite loop when given a #p"pathname"

### ISSUE THREAD

**Issue by Zulu-Inuoe** [ruricolist/spinneret#35]
Using a literal pathname gets Spinneret in an infinite loop of trying to expand its value (see `spinneret::catch-output`)

test case:

```lisp
(with-html-string
  (:html
   (:head
    (:link #p"styles.css" :type "text/css"))))
```

I'd expect this to error instead, if pathnames are not supported.

Thanks!

**Comment by ruricolist** [comment]
Thanks for reporting this. Pathnames should definitely be supported. I'm
not at a computer today but I'll fix it as soon as I can.
