### ISSUE TITLE
Inserted spaces and <pre>

### ISSUE THREAD

**Issue by dfmorrison** [ruricolist/spinneret#38]
I think `*suppress-inserted-spaces* t` should be in effect by default when emitting a `<pre>`.

**Comment by ruricolist** [comment]
Can you give me an example? `fill-text` isn't called in a `<pre>`. Or are you nesting other HTML elements inside a `<pre>`?

**Comment by dfmorrison** [comment]
```
(with-html-string (:pre "foo" #\Newline "b" "a" "r")) ⇒
"<pre>foo 
 b a r</pre>"
```
Note the leading space before the 'b', as well as those between the strings in the second line. But with `*suppress-inserted-spaces* t` all seems well:

```
(let ((*suppress-inserted-spaces* t))
       (with-html-string (:pre "foo" #\Newline "b" "a" "r"))) ⇒
"<pre>foo
bar</pre>"
```
