### ISSUE TITLE
Line breaks should not be made automagically when emitting a <pre>

### ISSUE THREAD

**Issue by dfmorrison** [ruricolist/spinneret#39]
I don't think line breaks should be automagically inserted when emitting a `<pre>`. This appears to be a slightly different issue than the spaces.

**Comment by ruricolist** [comment]
Can you give me an example of this one?

Examples are helpful for understanding the problem, and they also let me add regression tests.

**Comment by ruricolist** [comment]
Does fixing #41 fix this as well?

**Comment by dfmorrison** [comment]
Well, this is embarrassing. I see I never entered an example, which was pretty stupid of me. But worse, now, I seem unable to reproduce what I think was the issue I thought, or perhaps imagined, I was seeing. Sorry about that!
