### ISSUE TITLE
Canvas

### ISSUE THREAD

**Issue by heylisp** [ruricolist/spinneret#49]
Hello,
I can't figure out how to use canvas. Is there any example code?
Is Javascript required?
Actually I'm using Weblocks: https://40ants.com/weblocks/quickstart.html
Please give me some hint!
Thank you very much!

**Comment by ruricolist** [comment]
You need JavaScript to use canvas elements, yes. Probably [Parenscript](https://common-lisp.net/project/parenscript/) would be a good place to start.

**Comment by heylisp** [comment]
> You need JavaScript to use canvas elements, yes. Probably [Parenscript](https://common-lisp.net/project/parenscript/) would be a good place to start.

Thanks ruricolist!
