### ISSUE TITLE
li tag not closed correctly

### ISSUE THREAD

**Issue by fstamour** [ruricolist/spinneret#58]
the simple code

```lisp
(spinneret:with-html-string
  (:li "stuff"))
```

returns

```lisp
"<li>stuff"
```

when it should return 

```lisp
"<li>stuff</li>"
```

**Comment by ruricolist** [comment]
That's deliberate; HTML no longer requires <li> tags to be closed.

**Comment by fstamour** [comment]
Would it be possible to override that behaviour? I was trying to use spinneret to generate templates (vuejs templates) and the templating engine was loudly complaining about the tag not being closed.

(On the other hand, I could open an issue on vuejs.)

**Comment by ruricolist** [comment]
There's an override. You can bind the  *html-style* variable to :tree.

**Comment by fstamour** [comment]
Ah, thanks!
