### ISSUE TITLE
Class keywords are not parsed properly

### ISSUE THREAD

**Issue by phoe** [ruricolist/spinneret#64]
```lisp
SPINNERET> (with-html (:div.my-class))
<div class=my-class></div>
NIL

SPINNERET> (interpret-html-tree '(:div.my-class))
<div.my-class>
</div.my-class>
NIL
```

**Comment by phoe** [comment]
Related question: the docs stay that the interpreter implements a "subset" of spinneret syntax. Is this subset specified somewhere and/or aims for feature parity with the macro facility? Maybe adding that to the docs could clarify some questions I've seen related to "can the spinneret interpreter do X or Y or do I need to depend on its macro code?".

**Comment by ruricolist** [comment]
I've added a line to the readme about the interpreter still being under development.

**Comment by phoe** [comment]
Thanks!
