### ISSUE TITLE
closing tag seems to missing

### ISSUE THREAD

**Issue by OrganicProgramming** [ruricolist/spinneret#65]
When I run following code (with SBCL 2.2.8 ):
```common lisp
(spinneret:with-html-string (:html (:body (:p "Test"))))
```
I get the following output:
```
"<html lang=en>
 <body>
  <p>Test
 </body>
</html>"
```
I.e. the closing `</p>` tag seems to be missing. 
Some weeks ago I did not observe this behavior so it could be introduced quite recently.

**Comment by boogsbunny** [comment]
same

**Comment by OrganicProgramming** [comment]
My bad, I learned today that the closing tag for <p> is not always needed. Thanks for the advice.
