### ISSUE TITLE
Spinneret escapes pre-formatted tags (in particular, <style>)

### ISSUE THREAD

**Issue by aartaka** [ruricolist/spinneret#66]
# Problem
When running this piece of code:
``` lisp
(spinneret:with-html
  (:style "a > p{
    color: white;
}"))
```
I get 
``` html
<style>a &gt; p{
    color: white;
}</style>
```
Which breaks browser's stylesheet processing and breaks this exact CSS rule because `&gt;` is not ever parsed as `>`. It should not be serialized this way, especially in preformatted tags.

# Guess
As far as I can tell, it happens because of `*pre*` special variable not being honored when escaping the body of the tag. But Spinneret has so many layers of printing that I'm unable to narrow it down more than:
``` lisp
(spinneret::with-tag (:style)
  "a > p{
    color: white;
}")
```
still producing the escaped output.

# What I've tried:
- `*print-pretty*` as NIL.
- `spinneret:*html-style*` as `:tree`.
- Using `<pre>` to learn if it's `<style>`-specific. It's not, all pre-formated tags are broken the same.

None un-escaped the contents of `<style>` or any other pre-formatted tag.

@ruricolist, any idea why that happens?

**Comment by aartaka** [comment]
Ahhhh, right! Thanks for that!

But then, should it be unescaped for `<style>`, `<script>` etc. by default? It would be extremely convenient...

**Comment by ruricolist** [comment]
My position is that experience over the decades with templating libraries has shown that implicitly leaving anything unescaped inevitably results in script injection.

That said, this behavior should be better documented. I will add examples of style and script tags in the readme.

**Comment by aartaka** [comment]
Fair! Feel free to close this issue afterwards :)
