### ISSUE TITLE
Reequest: Add Example with parenscript

### ISSUE THREAD

**Issue by omarbassam88** [ruricolist/spinneret#73]
I was not able to use spinneret with parenscript unfortunately. Can you pleease add more Documentaion or examples about it.
loading the spinneret/ps didn't help.

for example:
```lisp
(with-html-string
  (:script (ps
                  (defun greeting ()
                     (alert "Helo"))))
```
it escapes the `"` in "Helo" and doesn't interpret it as javascript string. The result of the `ps` macro is correct but the `with-html` or `with-html-string` mess it up for some reason.

**Comment by mooseyboots** [comment]
i have been trying to do much the same thing.

```
(with-html-string
  (:script (:raw (ps
                  (defun greeting ()
                     (alert "Hello")))))
```
will unfuck your `"`, which is a start.

**Comment by ruricolist** [comment]
Sorry, I missed this issue when it was opened. I've added a section on using ParenScript in Spinneret.
