### ISSUE TITLE
Attributes are not wrapped with ""

### ISSUE THREAD

**Issue by diasbruno** [ruricolist/spinneret#78]
Is there an option for this?

Using 

```lisp
:attrs (list :alt text :src link)
```

produces

```txt
alt=normal text like this src=link
```

**Comment by ruricolist** [comment]
I can't seem to reproduce this. Can you give more context?

For reference, what I see is:

```
(with-html (:img :attrs (list :alt text :src link)))
=> <img alt="my text" src=link>
```

**Comment by diasbruno** [comment]
:thinking: Is there some kind of list that controls which attributes to add the `""`?
I'm looking for a way to wrap all attributes with `""`.

**Comment by diasbruno** [comment]
It seems that `need-quotes?` controls this.

https://github.com/ruricolist/spinneret/blob/master/syntax.lisp#L31

**Comment by ruricolist** [comment]
So to be clear, you want a configuration option that forces all attributes to be quoted? That would be easy to add.

**Comment by diasbruno** [comment]
Yep. `*always-quote*` would be ok? I think I can make a PR for it.

**Comment by ruricolist** [comment]
Sure, go ahead.
