### ISSUE TITLE
Suppress new lines?

### ISSUE THREAD

**Issue by jmercouris** [ruricolist/spinneret#89]
Hello, trying the following I get:

```
(spinneret:with-html-string (:body
                                   (:p "hello")))
"<body>
 <p>hello
</body>"
```

whereas I am trying to get:

```
<body><p>hello</body>
```

I tried looking through the documentation but wasn't able to find something. Any help is appreciated, thank you.

**Comment by ruricolist** [comment]
You can bind `*print-pretty*` to nil to prevent inserting indentation and newlines.

**Comment by jmercouris** [comment]
I see, thank you.
